messages:
  does-not-own-color: '&cYou do not own the ChatColor %color%'
  does-not-own-modifier: '&cYou do not own the Modifier %modifier%'
  set-chatcolor: '&aYour ChatColor has been set to %color%'
  set-modifier: '&aYour Modifier has been set to %modifier%'

chatcolor-gui-name: '&aC&bH&eA&8T &6C&3O&2L&rO&4R'
modifiers-gui-name: '&cCHAT &4MODIFIERS'